spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jobify_test
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

email:
  email-enabled: false